### PR TITLE
Clean up tests, dialyzer and xref build targets; update rebar

### PR DESCRIPTION
**Pull request by hazen**
- Removed extra `rebar-test.config` as unknown functions were required for dialyzer
- Updated all rebar dependencies to be within Basho
- Updated the version of rebar to 2.5.1
- Added `ifdef` around testing sections
- Removed some unused functions per dialyzer complaint
- Added `xref_checks` option to `rebar.config` to get xref to pass (weird unused exported function warnings otherwise)
- Enabled Thumbs for builds

### CODE REVIEW

**Comment by ooshlablu** [comment]
Test test test

**Comment by davidx** [comment]
😃

**Comment by hazen** [comment]
```
Test Results:
test_hll-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
---------------------------------------------
0 Tests Failed
1 Tests Passed
That's 100.0% for those keeping score
```

**Comment by JeetKunDoug** [comment]
+1

**Comment by JeetKunDoug** [comment]
@fadushin caught a bug in `hyper:estimate_report` - it doesn't actually complete because the pattern match is bad. Running `make estimate-report` results in:

```
{"init terminating in do_boot",{{badmatch,[[ok,ok,ok,ok,ok],[ok,ok,ok,ok,ok],
[ok,ok,ok,ok,ok],[ok,ok,ok,ok,ok],[ok,ok,ok,ok,ok],[ok,ok,ok,ok,ok]]},
[{hyper,estimate_report,0,[{file,"src/hyper.erl"},
{line,274}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by JeetKunDoug** [comment]
+1

**Pull request merged**
