### PR TITLE
Merge Game Analytics upstream changes - including license changes (switch to MIT)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by russelldb** [comment]
Nice.

**Comment by ghost** [comment]
Nice, except from [develop-2.2 + ](https://github.com/basho/riak_kv/blob/develop-2.2/rebar.config) we work with a tagged version of hyper ("1.0.0"). 

```
{hyper, ".*", {git, "https://github.com/basho/hyper", {tag, "1.0.0"}}},
```

The tag "1.0.0" corresponds to the 'basho' branch of basho/hyper.

basho/hyper also contains a branch called upstream/master which corresponds to gameanalytics/hyper master branch. 

Oh the joy of Basho branch discipline 😐.

The 'basho' branch looks really divergent from gameanalytics master - I'm not sure how cleanly it will apply. 

Anyhow, this p/r needs to die, so I'll close it now.
https://github.com/basho/hyper/commit/f6ed834cd8799623ec00faaedc9ef2a55876d5d8

There is some sense though - because master (corresponds to upstream master) version just works off master of bisect project and that doesn't work because it depends upon master of 'proper' project which in turn just dies unless run using Erlang greater >= 17 ... which of course Riak won't compile with because, priorities.

**Comment by ghost** [comment]
Actually, who cares - all we really want to get the changeset with the license changes into the project - and from there cherry pick the changes to c_array into the basho branch. So actually, there is no testing or anything necessary, because this branch isn't even used anyway.

**Comment by russelldb** [comment]
Looks good to me. If I had the bit, I'd +1 and merge this now.

**Pull request merged**
